function [AET,actEvapCanopy,actEvapGrnd,actTranspir,latentHeat,PET]=...
    LatentHeat(feedback,dt,nCells,hasSnow,isOverstory,isBare,...
    RaC,TSurfTemp,airDens,press,eActAir,VPD,LAI,rainfall,...
    elevation,Tair,netShort,netRadET,hasCanopySnow,...
    depth1,rarc,r0c,RGL,b_infilt,moist_resid,WmVeg,Wcr,Wwp,Wm,...
    WVegOrg,W,ice,root,SS0)
%% Algorithm Description
% 
%% output
% AET (-mm/s): actual total evapotraspiration
% actEvapCanopy (-mm/s): evaporation from intercepted rain
% actTranspir (-mm/s): evaporated vapor due to transpiration
% actEvapGrnd (-mm/s): vapor flux due to sublimation
% latentHeat -W/(m^2)/s: total latent heat by ET or evap+sublimation
% PET (-mm/s): Potential ET
%% input
global m2mm RHO_W Lv0 Lv1
% no overstory
nLayers=size(W,2);
AET=zeros(nCells,1);
PET=zeros(nCells,1);
actEvapGrnd=zeros(nCells,1);
actEvapCanopy=zeros(nCells,1);
actTranspir=zeros(nCells,nLayers);
noOverOrBare=~(isOverstory|isBare|hasSnow);
% Wa=sum(this.W,2);
if any(noOverOrBare)
%     [AET(noOverOrBare),actEvapCanopy(noOverOrBare),...
%     actEvapGrnd(noOverOrBare),actTranspir(noOverOrBare,:)] = ...
%     canopy_ET(feedback, dt, elevation(noOverOrBare), WmVeg(noOverOrBare),WVegOrg(noOverOrBare),... 
%             SS0(noOverOrBare),root(noOverOrBare,:), Wcr(noOverOrBare,:), Wwp(noOverOrBare,:), ...
%             W(noOverOrBare,:),ice(noOverOrBare,:), ...
%             airDens(noOverOrBare),press(noOverOrBare),rainfall(noOverOrBare),Tair(noOverOrBare),...
%             TSurfTemp(noOverOrBare),eActAir(noOverOrBare),VPD(noOverOrBare), LAI(noOverOrBare),netRadET(noOverOrBare), ...
%             netShort(noOverOrBare),RaC(noOverOrBare),rarc(noOverOrBare),...
%             r0c(noOverOrBare),RGL(noOverOrBare));
        
   [AET(noOverOrBare),actEvapCanopy(noOverOrBare),...
       actEvapGrnd(noOverOrBare),actTranspir(noOverOrBare,:),PET(noOverOrBare)]=...
    canopy_ET2(feedback,dt,elevation(noOverOrBare),...
    WmVeg(noOverOrBare),WVegOrg(noOverOrBare),...
    SS0(noOverOrBare),root(noOverOrBare,:),Wcr(noOverOrBare,:), Wwp(noOverOrBare,:),...
    W(noOverOrBare,:),ice(noOverOrBare,:),...% state variables
    rainfall(noOverOrBare),Tair(noOverOrBare),VPD(noOverOrBare),LAI(noOverOrBare),netRadET(noOverOrBare),...
    netShort(noOverOrBare),RaC(noOverOrBare),...% forcing
    rarc(noOverOrBare),r0c(noOverOrBare),RGL(noOverOrBare));% vegetation type specific
end
[actEvapBareSoil,actEvapBareGrnd,PETBare] =SoilSurf.arno_evap(nCells,hasSnow,isOverstory,isBare,feedback,dt,...
                                       netRadET,Tair,VPD,elevation,RaC,hasCanopySnow,...
                                       b_infilt,moist_resid,Wm,depth1,...
                                       SS0,W);
%mm to -mm/s,%CREST corrected, VIC commit a sign error here
AET=AET+actEvapBareSoil+actEvapBareGrnd;
% AET(this.hasSnow|this.isOverstory)=0;
AET=-AET/dt;
PET=PET+PETBare;
PET=-PET/dt;
actEvapCanopy(noOverOrBare)=-actEvapCanopy(noOverOrBare)/dt;
actTranspir=-actTranspir/dt;
actTranspir(:,1)=actTranspir(:,1)-actEvapBareSoil/dt;
actEvapGrnd=-(actEvapGrnd+actEvapBareGrnd)/dt;
Le= Lv0 + Lv1 * TSurfTemp;
latentHeat= Le.*AET/m2mm * RHO_W;
end