function SaveStates(this,resPath)
%% saves all variables at the given site during the simulation period to a excel file
disp('Saving Hydrographs...')
dates=[];
for ip=1:this.hydroSites.nPeriods
    if this.hydroSites.warmupDate(ip)>this.hydroSites.startDate(ip)
        dates=[dates,this.hydroSites.startDate(ip):this.hydroSites.timeStep:this.hydroSites.endDate(ip)];
    else
        dates=[dates,this.hydroSites.warmupDate(ip)+this.hydroSites.timeStep:this.hydroSites.timeStep:this.hydroSites.endDate(ip)];
    end
end
dates=dates';
switch this.timeMark
    case 'd'
        fmt='yyyy/mm/dd';
    case 'h'
        fmt='yyyy/mm/dd:HH';
    case 'u'
        fmt='yyyy/mm/dd:HH:MM';
end
for i=1:this.hydroSites.nSites
    if ischar(this.hydroSites.STCD{i})
        staName=this.hydroSites.STCD{i};
    else
        staName=num2str(this.hydroSites.STCD{i});
    end
    fileName=strcat(resPath,staName,'.csv');
    content=table(cellstr(datestr(dates,fmt)),...
        this.px_excS(:,i),this.px_excI(:,i),...
        this.px_runoff(:,i),this.hydroSites.runoff(:,i),...
        'VariableNames',...
        {'Date','ExcS','ExcI','R','R_Obs'});
%     content=table(cellstr(datestr(dates,fmt)),...
%         this.px_rain(:,i),this.px_snow(:,i),this.px_PET(:,i),...
%         this.px_EAct(:,i),this.px_SWE(:,i),...
%         this.px_iceSurf(:,i),this.px_WSurf(:,i),this.px_CCSurf(:,i),...
%         this.px_icePack(:,i),this.px_WPack(:,i),this.px_CCPack(:,i),...
%         this.px_intRain(:,i),this.px_intSnow(:,i),...
%         this.px_W(:,i),this.px_SM(:,i),...
%         ,...
%             this.px_RS(:,i),...
%         this.px_RI(:,i),...
%         this.px_runoff(:,i),this.hydroSites.runoff(:,i),...
%         'VariableNames',...
%         {'Date','rain','snow','PET','AET','SWE','SurfICE','SurfW','SurfCC',...
%         'PackICE','PackW','PackCC','intRain','intSnow','W','SM','excS','excI','RS','RI','R','R_Obs'});
    writetable(content,fileName,'Delimiter',',');
end
end