function RunoffAndRoutePre(obj,timeStep,coeM,expM,coeR,coeS,RunoffRows,RunofCols,hasRiverInterflow)
%prepares all basic data derived variables that remain constant over
%time and will be used in simulation.
%% intput parameters
% timeStep-coeS: please refer to the comments in ModelParameters.m
% (RunoffRows,RunoffCols) the (row,col) of pixels whose runoff will be computed
%%
obj.CalNextTime(coeM,expM,coeR,coeS,hasRiverInterflow);
[obj.SRowA,obj.SColA,obj.SFracA,...
obj.SRowB,obj.SColB,obj.SFracB,...
obj.RSPassedRow,obj.RSPassedCol,...
obj.RSStartedRow,obj.RSStartedCol]=obj.RouteTreat(timeStep,obj.nextTimeS,RunoffRows,RunofCols);
[obj.IRowA,obj.IColA,obj.IFracA,...
obj.IRowB,obj.IColB,obj.IFracB,...
obj.RIPassedRow,obj.RIPassedCol,...
obj.RIStartedRow,obj.RIStartedCol]=obj.RouteTreat(timeStep,obj.nextTimeI,RunoffRows,RunofCols);
end