function succeeded=ReadIntForcing(this,mode,taskType,core,nCore)
this.datePrecSto=this.ReadAForcVar(mode,taskType,this.dirIntPrec,this.datePrecSto,this.dateIntervalPrec,'prec',...
    this.fmtPrec,this.dateConvPrec,this.dirExtPrec,this.extPrec,this.bandPrec,...
    this.tsRatioPrec,this.tsTransPrec,this.uLimPrec,this.dLimPrec,...
    core,nCore);
this.dateSWSto=this.ReadAForcVar(mode,taskType,this.dirIntSW,this.dateSWSto,this.dateIntervalSW,'shortwave',...
    this.fmtSW,this.dateConvSW,this.dirExtSW,this.extSW,this.bandSW,...
    this.tsRatioSW,this.tsTransSW,this.uLimSW,this.dLimSW,...
    core,nCore);
this.dateLWSto=this.ReadAForcVar(mode,taskType,this.dirIntLW,this.dateLWSto,this.dateIntervalLW,'longwave',...
    this.fmtLW,this.dateConvLW,this.dirExtLW,this.extLW,this.bandLW,...
    this.tsRatioLW,this.tsTransLW,this.uLimLW,this.dLimLW,...
    core,nCore);
this.dateTairSto=this.ReadAForcVar(mode,taskType,this.dirIntTair,this.dateTairSto,this.dateIntervalTair,'Tair',...
    this.fmtTair,this.dateConvTair,this.dirExtTair,this.extTair,this.bandTair,...
    this.tsRatioTair,this.tsTransTair,this.uLimTair,this.dLimTair,...
    core,nCore);
this.dateHUSto=this.ReadAForcVar(mode,taskType,this.dirIntHU,this.dateHUSto,this.dateIntervalHU,'humidity',...
    this.fmtHU,this.dateConvHU,this.dirExtHU,this.extHU,this.bandHU,...
    this.tsRatioHU,this.tsTransHU,this.uLimHU,this.dLimHU,...
    core,nCore);
this.datePresSto=this.ReadAForcVar(mode,taskType,this.dirIntPres,this.datePresSto,this.dateIntervalPres,'pres',...
    this.fmtPres,this.dateConvPres,this.dirExtPres,this.extPres,this.bandPres,...
    this.tsRatioPres,this.tsTransPres,this.uLimPres,this.dLimPres,...
    core,nCore);
if strcmpi(this.typeWind,'UV')
    this.dateWindUSto=this.ReadAForcVar(mode,taskType,this.dirIntWindU,this.dateWindUSto,this.dateIntervalWindU,'windU',...
        this.fmtWindU,this.dateConvWindU,this.dirExtWindU,this.extWindU,this.bandWindU,...
        this.tsRatioWindU,this.tsTransWindU,this.uLimWindU,this.dLimWindU,...
        core,nCore);
    this.dateWindVSto=this.ReadAForcVar(mode,taskType,this.dirIntWindV,this.dateWindVSto,this.dateIntervalWindV,'windV',...
        this.fmtWindV,this.dateConvWindV,this.dirExtWindV,this.extWindV,this.bandWindV,...
        this.tsRatioWindV,this.tsTransWindV,this.uLimWindV,this.dLimWindV,...
        core,nCore);
    this.wind(this.basinMask)=sqrt(this.windU(this.basinMask).^2+this.windV(this.basinMask).^2);
%     if this.dateWindUSto==-1 || this.dateWindVSto
%     else
%     end
else
    this.dateWindSto=this.ReadAForcVar(mode,taskType,this.dirIntWind,this.dateWindSto,this.dateIntervalWind,'wind',...
        this.fmtWind,this.dateConvWind,this.dirExtWind,this.extWind,this.bandWind,...
        this.tsRatioWind,this.tsTransWind,this.uLimWind,this.dLimWind,...
        core,nCore);
end
LAIReset=datenum(1930,1,1);
this.dateLAISto=this.ReadAForcVar(mode,taskType,this.dirIntLAI,this.dateLAISto,this.dateIntervalLAI,'LAI',...
    this.fmtLAI,this.dateConvLAI,this.dirExtLAI,this.extLAI,this.bandLAI,...
    this.tsRatioLAI,this.tsTransLAI,this.uLimLAI,this.dLimLAI,...
    core,nCore,LAIReset);
    %     this.dateLAISto=dateToReadLAI;
if strcmpi(this.typeWind,'UV')
    succeeded=~any([this.datePrecSto,this.dateSWSto,this.dateLWSto,...
        this.dateTairSto,this.dateHUSto,this.datePresSto,...
        this.dateWindUSto,this.dateWindSto,this.dateLAISto]==-1);
else
    succeeded=~any([this.datePrecSto,this.dateSWSto,this.dateLWSto,...
        this.dateTairSto,this.dateHUSto,this.datePresSto,...
        this.dateWindSto,this.dateWindSto,this.dateLAISto]==-1);
end
end
